@id=263e082e-af48-4c5d-a4a0-df7dfcdb39a2

PUT https://localhost:7203/breakfasts/{{id}}
Content-Type: application/json

{
    "name": "Café da Manhã UPDATED 2",
    "description": "UHUU",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}